### ISSUE TITLE
Use internal I2C of Raspberry Pi

### ISSUE THREAD

**Issue by ozmy** [svenseeberg/data-diode#17]
Raspberry Pi has a built-in i2c port so you can connect the screen directly. This will reduce the cost of the device and increase reliability.
You should exclude USB UART adapters and connect the Raspberry PI directly using TTL ports. Cheaper and more reliable.

**Comment by svenseeberg** [comment]
Good idea. I never had a detailed look into I2C. Does that work unidirectional? I'm not sure if the protocol supports that.

**Comment by ajt68** [comment]
Extending using the onboard TTL port (TX one side to RX on the other), maybe pass the single connection through an opto-isolator so the direction cannot be reversed in an software hack/attack.

**Comment by svenseeberg** [comment]
> Extending using the onboard TTL port (TX one side to RX on the other), maybe pass the single connection through an opto-isolator so the direction cannot be reversed in an software hack/attack.

I tried that initially but could not get this to work, see https://www.mail-archive.com/misc@openbsd.org/msg179041.html

**Comment by svenseeberg** [comment]
Closed in favor of #20
